# Generated by Django 2.1.3 on 2018-12-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('content_title', models.CharField(max_length=255)),
                ('content_format', models.CharField(choices=[('pdf', 'pdf'), ('html', 'html')], max_length=5, null=True)),
                ('content', models.FileField(upload_to='content')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentDeveloper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_developer', models.CharField(max_length=255)),
                ('content_developer_url', models.URLField()),
                ('content_developer_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='content_developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.ContentDeveloper'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Level'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.ContentType'),
        ),
    ]
